defecttracking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('inputcs.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inputcs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('input/', views.InputView.as_view(), name='input'),  # Set root to home view    
    path('defect-input/', views.DefectFormView.as_view(), name='defect-input'
    ),
    # path('ajax-form/', views.AjaxFormView.as_view(), name='ajax'
    # ),
    path('home2/', views.HomeView2.as_view(), name='home2'),
    path('home2/create_post/', views.create_post, name='create_post'),
    path('ajaximage/', views.ajaximage, name='ajaximage'),
]

inputcs/models.py
import json
from django.db import models
# from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Sheet(models.Model):
    """
    Represents a Defect Tracking
    """
    PROCESS_CHOICES = [
        ('S1', 'S1'),
        ('S2', 'S2'),
        ('S3', 'S3'),
        ('S4', 'S4'),
        ('S5', 'S5'),
        ('S6', 'S6'),
        ('S7', 'S7'),
        ('S8', 'S8'),
        ('S9', 'S9'),
        ('S10', 'S10'),
        ('S11', 'S2'),
        ('S12', 'S2'),
        ('ED', 'ED'),
    ]
    DEFECT_CHOICES = [
        ('XS' , 'Excess'),
        ('WL' , 'Waterleak'),
        ('PH' , 'Pin Hole'),
        ('F' , 'Flick'),
        ('ED R' , 'ED run'),
        ('ED B' , 'ED Blister'),
        ('NS' , 'No Spat'),
        ('OF' , 'Off Location'),
        ('MC' , 'Missing Clip'),
        ('PA' , 'Poor Application'),
        ('NB' , 'No Brush'),
        ('G' , 'Gap'),
        ('MAS' , 'Mastic'),
        ('BB' , 'Body Bound'),
    ]
    process = models.CharField(max_length=30, choices=PROCESS_CHOICES, null=False)
    defect = models.CharField(max_length=30, choices=DEFECT_CHOICES, null=False)
    # location = models.CharField(max_length=50, null=False )
    created = models.DateTimeField(auto_now_add=True)  # Sets on create
    period = models.CharField(max_length=30, null=False, choices=[('1st', '1st'), ('2nd','2nd'), ('3rd','3rd'), ('4th','4th')])
    coorx = models.FloatField(null=True, blank=True, default=None)
    coory = models.FloatField(null=True, blank=True, default=None)
    photo = models.ImageField(blank=True, null=True,)
    


class Post(models.Model):
    """
    Represents a Defect Tracking
    """
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    text = models.TextField()
    coord = models.TextField()

    # Time is a rhinocerous
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.text+' - '+self.author.username


class AjaxImage(models.Model):
    image_coord = models.FloatField()

    def __str__(self):
        return self.image_coord


#  ('S1', 'RS Mohican Channel'), 
#         ('S2', 'RS Mohican Channel') , 
#         ('S3', 'RS Firewall and Door Beads'),
#         ('S4', 'LS Firewall and Door Beads'),
#         ('S5', 'RS Rear Door and Hatch Hinge'),
#         ('S6', 'LS Rear Door and Hatch Hinge'),
#         ('S7', 'RS Front Door and Trunck Brush'),
#         ('S8', 'LS Front Door and Trunck Brush'),
#         ('S9', 'RS HATCH and HOOD'),
#         ('S10', 'LS HATCH and HOOD'), 
#         ('S11', 'RS Lower Trough and Body Combi'),
#         ('S12', 'RS Lower Trough and Body Combi'),

inputcs/forms.py
# blog/forms.py

from django import forms
from . import models


class SheetForm(forms.ModelForm):
    class Meta:
        model = models.Sheet
        fields = [
            'process',
            'defect',
            'period',
            'coorx',
            'coory',
            'photo',
        ]
        widgets = {
            'coorx': forms.HiddenInput(),
            'coory': forms.HiddenInput(),
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        # exclude = ['author', 'updated', 'created', ]
        fields = ['text']
        widgets = {
            'text': forms.TextInput(
                attrs={'id': 'post-text', 'required': True, 'placeholder': 'Say something...'}
            ),
        }

class AjaxImageForm(forms.ModelForm):
    class Meta:
        model = models.AjaxImage
        fields = ['image_coord']

inputcs/views.py
from django.shortcuts import render, HttpResponse
# from django.db.models import Count
from django.views.generic.base import TemplateView
from django.utils import timezone
from django.urls import reverse_lazy, reverse  
from django.contrib import messages
from django.views.generic import ListView, DetailView, FormView, CreateView
from . import models, forms
from inputcs.models import Post, AjaxImage, Sheet
from inputcs.forms import PostForm, AjaxImageForm
import json

from django.http import HttpResponse, JsonResponse, Http404
# from django.shortcuts import render
# from django.http import HttpResponse
# from django.db.models import F

class HomeView(TemplateView):
    """
    The CS homepage
    """
    template_name = 'inputcs/home.html'

    def get_context_data(self, **kwargs):
        sheet_form = forms.SheetForm
        context = super().get_context_data(**kwargs)
        
        context['sheet_form'] = sheet_form
        
        return context
    
class InputView(TemplateView):
    """
    Defect input
    """
    template_name = 'inputcs/input.html'

    def get_context_data(self, **kwargs):
        sheet_form = forms.SheetForm

        context = super().get_context_data(**kwargs)
        
        context['sheet_form'] = sheet_form
        
        return context


class DefectFormView(CreateView):
    model = models.Sheet
    success_url = reverse_lazy('home')
    fields = [
        'process',
        'defect',
        'period',
        'coorx',
        'coory',
        'photo',
    ]
    
    def form_valid(self, form):
        messages.add_message(
        self.request,
        messages.SUCCESS,
        'Thank you! Defect saved'
    )
        return super().form_valid(form)

class HomeView2(TemplateView):
    """
    The CS homepage2
    """
    template_name = 'inputcs/home2.html'

def create_post(request):
    if request.method == 'POST':
        post_text = request.POST.get('the_post')
        post_coord = request.POST.get('the_coord')
        response_data = {}

        post = Post(text=post_text, author=request.user, coord=post_coord)
        post.save()

        response_data['result'] = 'Create post successful!'
        response_data['postpk'] = post.pk
        response_data['text'] = post.text
        response_data['coord'] = post.coord
        response_data['created'] = post.created.strftime('%B %d, %Y %I:%M %p')
        response_data['author'] = post.author.username

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )


def ajaximage(request):
    coord = AjaxImage.objects.order_by('-id')[:5]
    # context = { 'coord' : coord }
    form = AjaxImageForm()
    if request.method == "POST" and request.is_ajax():
        form = AjaxImageForm(request.POST)
        if form.is_valid():
            image_coord = form.cleaned_data['image_coord']
            form.save()
            return JsonResponse({"image_coord": image_coord}, status=200)

    return render(request, "inputcs/imageajax.html", {'form':form})
    

# class AjaxFormView(CreateView):
#     model = models.Ajaxd
#     success_url = reverse_lazy('ajax')
#     fields = [
#         'test',
#     ]
    
#     def form_valid(self, form):
#         messages.add_message(
#             self.request,
#             messages.SUCCESS,
#             'Thank you! Your message has been sent.'
#         )
#         return super().form_valid(form)

inputcs/templates/inputcs/ajaxd_form.html
{% load static %}

{# inputcs/templates/inputcs/sheet_form.html #}
{% load static %}

{% load crispy_forms_tags %}



<form id='post-form' action="{% url 'ajax' %}" method="post" enctype="multipart/form-data" novalidate>
  {% csrf_token %}
  <div class="row">
    <div class="col-md-6 mb-3">
      <label for="test">Test: </label>
      {{ form.test }}
      <div class="invalid-feedback">
      Valid first name is required.
      </div>
    </div>
  </div>
    <tr>
      <td></td>
      <button type="submit" class="btn btn-primary">Submit</button>
      <!-- <td><button onclick="download()">Download</button></td>
      <td><button onclick="clearCanvas()">Clear</button></td> -->

    </tr>

    
</form>

  
<script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>


<script src="{% static 'inputcs/js/ajax_django.js' %}"></script>

inputcs/templates/inputcs/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>{% block title%} {% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'inputcs/dist/css/bootstrap.min.css'%}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'inputcs/dist/css/starter-template.css' %}" rel="stylesheet">
    
  </head>
  <body>
   
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static 'inputcs/images/tmmclogo.png' %}" width="30" height="30" alt="TMMC - logo">
    South Paint - Sealer CS
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}"> Defect List <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'input' %}">Input Defect <span class="sr-only">(current)</span></a>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> -->
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

<main role="main" class="container">

{% block content %}

{% endblock %}


</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="{% static "inputcs/js/vendor/jquery.slim.min.js" %}"><\/script>')</script><script src="{% static 'inputcs/dist/js/bootstrap.bundle.min.js' %}"></script>
      {% block javascript %}

      {% endblock %}
     
      </body>
      </html>

inputcs/templates/inputcs/base_temp.html
{% load static %}


<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>{% block title%} {% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sticky-footer-navbar/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'inputcs/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Favicons -->
<!-- <link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png"> -->
<link rel="manifest" href="{% static 'inputcs/favicons/manifest.json' %}">
<!-- <link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c"> -->
<!-- <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico"> -->
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'inputcs/css/sticky-footer-navbar.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex flex-column h-100">
    <header>
  <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    
      <img class="navbar-brand" src="{% static 'inputcs/images/tmmclogo.png' %}" alt="TMMC" width="50">
      <a class="navbar-brand" href="#">Paint Shop - Sealer CS</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home'%}">Defect List <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'input'%}">Input CS</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
      </div>
    </nav>    
  
</header>

<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container">
    {% block content %}

    {% endblock %}
  </div>
</main>

<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
</script>
      <script>window.jQuery || document.write('<script src="{% static "inputcs/js/jquery-3.5.1.slim.min.js" %}"><\/script>')
      </script>
      <script src="{% static 'inputcs/js/bootstrap.bundle.min.js' %}">
      </script>

{% block javascript %}5

{% endblock %}
    </body>

</html>

inputcs/templates/inputcs/home.html
<!-- Showing defects and filter  -->
{% extends "inputcs/base.html" %}

{% block title %} Home - Defects list {% endblock %}

{% load static %}

{% block content %}

<div class="row">

    <div class="col-md-12 col-lg-5 order-md-first">
        <h4 class=""><span class="text-muted">Last 10 Defects</span> </h4>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Defect</th>
                <th scope="col">Process</th>
                <th scope="col">Date & Time</th>
                <th scope="col">Period</th>
              </tr>
            </thead>
            <tbody>
                {% for i in defects %}
              <tr>
                <th scope="row">{{ i.id }}</th>
                <td>{{ i.defect }}</td>
                <td>{{ i.process }}</td>
                <td>{{i.created|date:'Y-m-d H:i'}}</td>
                <td>{{ i.period }}</td>
              </tr>
                {% endfor %}
              
            </tbody>
          </table>
    </div>

    <div class="col-md-12s col-lg-7">

        <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Car Body</span>
            <!-- <span class="badge bg-secondary rounded-pill">3</span> -->
          </h4>
        <img src="{% static 'inputcs/images/body_Rx.jpg' %}" id="reference-img" alt="" style="display: none"/>
            <div>
                <canvas width="600" height="450" id="drawing-canvas">
    
                </canvas>
            </div>
                <div style="padding-top:20px;">
                    <div id="coord"></div>
                </div>
    </div>

</div>
<!-- <div class="row">
    <div class="col-sm-1 border bg-light">    
        <h7>Num.: </h7>
    </div>
    <div class="col-sm-1 border bg-light">
            <h7> Defect </h7>
    </div>
    <div class="col-sm-1 border bg-light">
        <h7> Process </h7>
    </div>  
    <div class="col-sm-2 border bg-light">
        <h7> Date and Time </h7>
    </div>  
    <div class="col-sm-1 border bg-light">
        <h7>Period:</h7>
    </div>
</div>
{% for i in defects %}
<div class="row flex-nowrap">
    <div class="col-sm-1 border">    
        <span class="text-muted"> {{ i.id }}  </span>
    </div>
    <div class="col-sm-1 border">
        <span class="text-muted"> {{ i.defect }} </span>
    </div>
    <div class="col-sm-1 border">
        <span class="text-muted"> {{ i.process }} </span>
    </div>
    <div class="col-sm-2 border">
        <span class="text-muted"> {{i.created|date:'Y-m-d H:i'}}</span>
    </div>
    <div class="col-sm-1 border">
        <span class="text-muted">{{ i.period }}</span>
    </div>
</div>
    
        {% endfor %} -->

    
<!--     
    <div class="mt-5 col-md-5 order-md-1">

        <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Right Side CS </span> -->
            <!-- <span class="badge bg-secondary rounded-pill">3</span> -->
          <!-- </h4>
        <img src="{% static 'inputcs/images/left_body22.jpg' %}" id="reference-img2" alt="" style="display: none"/>
            <div>
                <canvas height="500" id="drawing-canvas2">
    
                </canvas>
            </div>
                <div style="padding-top:20px;">
                    <div id="coord"></div>
                </div>
    </div>
</div>     -->



       
{% endblock %}
 {% block javascript %}
        <script >
    
            var canvas;
            var ctx;
            var refImage;
    
            $(document).ready(function() {
            canvas = document.getElementById('drawing-canvas');
            ctx = canvas.getContext('2d');
            refImage = document.getElementById('reference-img');
            drawImageScaled(refImage, ctx);
                ctx.font = '22px normal'
                ctx.fillStyle = 'red';
                {% for i in defects %}
                ctx.fillText("{{ i.id }}", "{{i.coorx}}", "{{i.coory}}");
                {% endfor %}
            // $(canvas).click(function(e) {
            //     const offset = $(this).offset();
            //     const x = (e.pageX - offset.left) - 5;
            //     const y = (e.pageY - offset.top) + 10;
            //     ctx.font = '22px normal'
            //     ctx.fillStyle = 'red';
            //     ctx.fillText("{{ i.id }}", x, y);
                // console.log(ctx, refImage)
                // console.log(x, y);
                // console.log(e.pageX);
                // console.log(offset);
            });
    
            function drawImageScaled(img, ctx) {
            var canvas = ctx.canvas;
            var hRatio = canvas.width / img.width;
            var vRatio = canvas.height / img.height;
            var ratio  = Math.min ( hRatio, vRatio );
            var centerShift_x = ( canvas.width - img.width*ratio ) / 2;
            var centerShift_y = ( canvas.height - img.height*ratio ) / 2;  
            ctx.clearRect(0,0,canvas.width, canvas.height);
            ctx.drawImage(img, 0,0, img.width, img.height,
                                centerShift_x,centerShift_y,img.width*ratio, img.height*ratio);
            }
    
    
        </script>




        {% endblock %}

inputcs/templates/inputcs/input.html
{% extends 'inputcs/base.html' %}
{% load static %}

       


{% block content %}

{% with form=sheet_form %}
    {% include "inputcs/sheet_form.html" %}
{% endwith %}
  
{% block javascript %}

<script>
   

   var canvas;
   var ctx;
   var refImage;

   $(document).ready(function() {
     canvas = document.getElementById('drawing-canvas');
     ctx = canvas.getContext('2d');
     refImage = document.getElementById('reference-img');
     drawImageScaled(refImage, ctx);            
   
     $(canvas).click(function(e) {
       const offset = $(this).offset();
       const x = (e.pageX - offset.left) - 5;
       const y = (e.pageY - offset.top) + 10;
       ctx.font = '22px normal'
       ctx.fillStyle = 'red';
      
       if (ctx.fillText) {
         var answer = window.confirm("Save data?");
           if (answer) {
               ctx.fillText('X', x, y);
               $(canvas).off('click');//some code
             }
           else {
           context.clearRect(0, 0, canvas.width, canvas.height);
           }
         }       
       // console.log(x, y);
       document.getElementById('coorx').value = x;
       document.getElementById('coory').value = y;
     });
     
   });
   
   function drawImageScaled(img, ctx) {
     var canvas = ctx.canvas;
     var hRatio = canvas.width / img.width;
     var vRatio = canvas.height / img.height;
     var ratio  = Math.min ( hRatio, vRatio );
     var centerShift_x = ( canvas.width - img.width*ratio ) / 2;
     var centerShift_y = ( canvas.height - img.height*ratio ) / 2;  
     ctx.clearRect(0,0,canvas.width, canvas.height);
     ctx.drawImage(img, 0,0, img.width, img.height,
                         centerShift_x,centerShift_y,img.width*ratio, img.height*ratio);  
    }
   
   
   </script>
{% endblock %}   
      
       
                
{% endblock %}

inputcs/templates/inputcs/sheet_form.html
{# inputcs/templates/inputcs/sheet_form.html #}
{% load static %}

{% load crispy_forms_tags %}

<div class="row">

  <div class="col-md-7 col-lg-7">
    <h4 class="mb-3">Body Image </h4>
    <p> Click on the image to add a defect </p>
    <a href="{% url 'input'%}"> Clear Picture </a>
  
        <div style="width:300px;">
            <img src="{% static 'inputcs/images/body_Rx.jpg' %}" id="reference-img" alt="" style="display: none"/>
            <div><canvas width="600"   height="450" id="drawing-canvas" style="border:1px solid #000000;"></canvas></div>
            <div style="padding-top:20px;">
                <div id="coord"></div>
            </div>
        </div>
      
  </div>
      
  <div class="col-md-8 col-lg-5 order-md-last">
    <h4>Complete the form and click submit</h4>
    <form action="{% url 'defect-input' %}" method="post" enctype="multipart/form-data" novalidate>
          {% csrf_token %}
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="Process">Process: </label>
            {{ form.process }}
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="Period">Period: </label>
            {{ form.period }}
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="Defect">Defect: </label>
            {{ form.defect }}
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="photo">Photo: </label>
            {{ form.photo }}
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
        </div>

          <!-- <div class="col-md-6 mb-3">
            <label for="Location">Location: </label>
            {{ form.location }}
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div> -->
          <!-- <div class="col-md-6 mb-3">
            <label for="Coorx">Coorx: </label> -->
            <input id = "coorx" type="hidden" name="coorx" maxlength="20" required="" id="id_coorx">    
            <!-- <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div> -->
          <!-- <div class="col-md-6 mb-3">
            <label for="Coory">Coory: </label> -->
            <input id = "coory" type="hidden" name="coory" maxlength="20" required="" id="id_coory">    
            <!-- <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div> -->
        <!-- </div> -->

  
      
      <tr>
      <td></td>
      <button type="submit" class="btn btn-primary">Submit</button>
      <!-- <td><button onclick="download()">Download</button></td>
      <td><button onclick="clearCanvas()">Clear</button></td> -->

      </tr>

  

</div>
    
</form>